include: package:very_good_analysis/analysis_options.9.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
  exclude: 
    - '**/*.g.dart'
  plugins:
    - custom_lint