targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          - lib/routing/router_notifier.dart
      json_serializable:
        generate_for:
          - lib/data/dtos/**.dart