name: tsks_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  fpdart: ^1.1.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
