name: tsks_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  fpdart: ^1.1.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
