// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FSj-iImnIcQekB8hYY5WhYHJuqjZqck',
    appId: '1:928197699098:web:596d657fab0cc16aba93a3',
    messagingSenderId: '928197699098',
    projectId: 'tsks-37ec6',
    authDomain: 'tsks-37ec6.firebaseapp.com',
    storageBucket: 'tsks-37ec6.firebasestorage.app',
    measurementId: 'G-Q207YLPXP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUy8J7tg2kKtvLH7MJSgiz7U24QX_j39k',
    appId: '1:928197699098:android:74f6dae6a8164f8bba93a3',
    messagingSenderId: '928197699098',
    projectId: 'tsks-37ec6',
    storageBucket: 'tsks-37ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaesXKYzOO1KIjGc5IFbrv6DnzAPUjtc',
    appId: '1:928197699098:ios:aed51307df9d834fba93a3',
    messagingSenderId: '928197699098',
    projectId: 'tsks-37ec6',
    storageBucket: 'tsks-37ec6.firebasestorage.app',
    iosBundleId: 'com.example.tsksFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkaesXKYzOO1KIjGc5IFbrv6DnzAPUjtc',
    appId: '1:928197699098:ios:aed51307df9d834fba93a3',
    messagingSenderId: '928197699098',
    projectId: 'tsks-37ec6',
    storageBucket: 'tsks-37ec6.firebasestorage.app',
    iosBundleId: 'com.example.tsksFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2FSj-iImnIcQekB8hYY5WhYHJuqjZqck',
    appId: '1:928197699098:web:219de6caa8eb4eafba93a3',
    messagingSenderId: '928197699098',
    projectId: 'tsks-37ec6',
    authDomain: 'tsks-37ec6.firebaseapp.com',
    storageBucket: 'tsks-37ec6.firebasestorage.app',
    measurementId: 'G-KZDNXZ7T1N',
  );
}
